version: "3.8"

services:
    nginx:
        container_name: nginx
        build:          ./requirements/nginx/
        image:          nginx:inception
        env_file:       .env
        networks:
            - inception
        ports:
            - "443:443"
        restart:        always
        volumes:
            - web_v:/var/www/html/
        depends_on:
            - wordpress
    
    mariadb:
        container_name: mariadb
        build:          ./requirements/mariadb/
        image:          mariadb:inception
        env_file:       .env
        networks:
            - inception
        restart:        always
        volumes:
            - database_v:/var/lib/mysql/
    
    wordpress:
        container_name: wordpress
        build:          ./requirements/wordpress/
        image:          wordpress:inception
        env_file:       .env
        networks:
            - inception
        restart:        always
        volumes:
            - web_v:/var/www/html/
        depends_on:
            - mariadb

networks:
    inception:
        name:   inception

volumes:
    database_v:
        driver_opts:
            type: none
            o: bind
            device: /home/SCRIPT_TO_CHANGE_ME/data/database
    web_v:
        driver_opts:
            type: none # Custom type: not tmpfs or nfs,see next option `o`
            o: bind # What type to use, a dir from the host. 
            device: /home/SCRIPT_TO_CHANGE_ME/data/web